In [1]:
import pandas as pd
import numpy as np
import math

# Get Data Through Order Table

In [2]:
import pandas as pd

# df = pd.read_csv(r"C:\Users\nanduji\Desktop\IotaAcadmey_DataAnalytic\python programing\Project file\python project files\Kite_Pnl_Project\orders (1).csv")
df = pd.read_csv("orders (1).csv")
df.head()

,Time,Type,Instrument,Product,Qty.,Avg. price,Status
0,18/12/2021 10:23,SELL,SBI,CNC,1000/1000,525.25,COMPLETE
1,16/12/2021 15:08,BUY,ASHOKLEY,MIS,1000/1000,125.70,COMPLETE
2,16/12/2021 15:08,BUY,SBI,CNC,1000/1000,520.80,COMPLETE
3,16/12/2021 14:13,BUY,TATAMOTORS,MIS,250/250,490.55,COMPLETE
4,16/12/2021 13:54,BUY,ASHOKLEY,MIS,0/1000,127.10,CANCELLED

In [3]:
# clean cloumns

# Filter add for MIS prouduct and Complete status
df = df[(df['Product'] == 'MIS') & (df['Status'] == 'COMPLETE')].copy()
df
# df['excuted_qty'] =df['Qty.'].str.split[0].astype(int)

,Time,Type,Instrument,Product,Qty.,Avg. price,Status
1,16/12/2021 15:08,BUY,ASHOKLEY,MIS,1000/1000,125.70,COMPLETE
3,16/12/2021 14:13,BUY,TATAMOTORS,MIS,250/250,490.55,COMPLETE
5,16/12/2021 13:21,SELL,TATAMOTORS,MIS,250/250,492.10,COMPLETE
7,16/12/2021 12:39,SELL,ASHOKLEY,MIS,1000/1000,125.96,COMPLETE
8,16/12/2021 12:29,BUY,ASHOKLEY,MIS,2000/2000,125.70,COMPLETE
9,16/12/2021 11:22,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE
11,16/12/2021 10:46,SELL,ASHOKLEY,MIS,2000/2000,125.95,COMPLETE
12,16/12/2021 10:24,BUY,ASHOKLEY,MIS,1000/1000,125.60,COMPLETE
13,16/12/2021 10:23,BUY,ASHOKLEY,MIS,1000/1000,125.65,COMPLETE

In [4]:
# Clean Qty column : take the part before'/' and covert to interger
# df['Qty.'] = df['Qty.'].str.split('/').str[0].astype(int) it sho
# Notes above code is give error becuase already have Qty is interger value then we change it str and after interger

df['Qty.'] = df['Qty.'].astype(str).str.split('/').str[0].astype(int)
df

                Time  Type  Instrument Product  Qty.  Avg. price    Status
1   16/12/2021 15:08   BUY    ASHOKLEY     MIS  1000      125.70  COMPLETE
3   16/12/2021 14:13   BUY  TATAMOTORS     MIS   250      490.55  COMPLETE
5   16/12/2021 13:21  SELL  TATAMOTORS     MIS   250      492.10  COMPLETE
7   16/12/2021 12:39  SELL    ASHOKLEY     MIS  1000      125.96  COMPLETE
8   16/12/2021 12:29   BUY    ASHOKLEY     MIS  2000      125.70  COMPLETE
9   16/12/2021 11:22  SELL    ASHOKLEY     MIS  2000      125.95  COMPLETE
11  16/12/2021 10:46  SELL    ASHOKLEY     MIS  2000      125.95  COMPLETE
12  16/12/2021 10:24   BUY    ASHOKLEY     MIS  1000      125.60  COMPLETE
13  16/12/2021 10:23   BUY    ASHOKLEY     MIS  1000      125.65  COMPLETE

In [5]:
# Calculate Turnover(Quantity  * Price)

df['Turnover'] = df['Qty.'] * df['Avg. price']
df

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover
1,16/12/2021 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0
3,16/12/2021 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5
5,16/12/2021 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0
7,16/12/2021 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0
8,16/12/2021 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0
9,16/12/2021 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0
11,16/12/2021 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0
12,16/12/2021 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0
13,16/12/2021 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0

In [6]:
# Calculate Brokerage( capped at 20 or 0.03%)

df['Brokerage'] = df['Turnover'].apply(lambda x: min(x * 0.0003, 20))
df

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage
1,16/12/2021 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20
3,16/12/2021 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20
5,16/12/2021 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20
7,16/12/2021 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20
8,16/12/2021 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20
9,16/12/2021 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20
11,16/12/2021 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20
12,16/12/2021 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20
13,16/12/2021 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20

In [7]:
# STT/CTT = 0.025% on sell side only
df['STT/CTT'] = df.apply( lambda trade: trade['Turnover'] * 0.00025 if trade['Type'] == 'SELL' 
                          else 0, axis=1
)
df

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage,STT/CTT
1,16/12/2021 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20,0.00000
3,16/12/2021 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20,0.00000
5,16/12/2021 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20,30.75625
7,16/12/2021 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20,31.49000
8,16/12/2021 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20,0.00000
9,16/12/2021 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20,62.97500
11,16/12/2021 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20,62.97500
12,16/12/2021 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20,0.00000
13,16/12/2021 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20,0.00000

In [8]:
# calculate ETC(Exchange-Traded Commodity) Charges (0.0325) according to the NSE(National stock Exchange)
df['ETC'] = df['Turnover'] * 0.0000307
df

# Calcualte SEBI charge - according to Zerodha is per 10 cr =  0.0001%
df['SEBI'] =df['Turnover'] * 0.000001
df

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage,STT/CTT,ETC,SEBI
1,16/12/2021 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20,0.00000,3.858990,0.125700
3,16/12/2021 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20,0.00000,3.764971,0.122637
5,16/12/2021 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20,30.75625,3.776868,0.123025
7,16/12/2021 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20,31.49000,3.866972,0.125960
8,16/12/2021 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20,0.00000,7.717980,0.251400
9,16/12/2021 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20,62.97500,7.733330,0.251900
11,16/12/2021 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20,62.97500,7.733330,0.251900
12,16/12/2021 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20,0.00000,3.855920,0.125600
13,16/12/2021 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20,0.00000,3.857455,0.125650

In [9]:
# Tax levied by the government on the services rendered. 18% of ( brokerage + SEBI charges + transaction charges)
# Calcualte Gst - (18% on brokerage + etc + sebi) 
df['GST'] =(df['Brokerage'] + df['ETC'] + df['SEBI']) * 0.18
df

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage,STT/CTT,ETC,SEBI,GST
1,16/12/2021 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20,0.00000,3.858990,0.125700,4.317244
3,16/12/2021 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20,0.00000,3.764971,0.122637,4.299770
5,16/12/2021 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20,30.75625,3.776868,0.123025,4.301981
7,16/12/2021 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20,31.49000,3.866972,0.125960,4.318728
8,16/12/2021 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20,0.00000,7.717980,0.251400,5.034488
9,16/12/2021 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20,62.97500,7.733330,0.251900,5.037341
11,16/12/2021 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20,62.97500,7.733330,0.251900,5.037341
12,16/12/2021 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20,0.00000,3.855920,0.125600,4.316674
13,16/12/2021 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20,0.00000,3.857455,0.125650,4.316959

In [10]:
# Calculatem stamp Charges (accordinding Equity intraday treding =  0.003%)
df['Stamp charges']=df.apply(lambda data: data['Turnover'] * 0.00003 if data['Type'] == 'BUY' else 0, axis=1)
df

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage,STT/CTT,ETC,SEBI,GST,Stamp charges
1,16/12/2021 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20,0.00000,3.858990,0.125700,4.317244,3.771000
3,16/12/2021 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20,0.00000,3.764971,0.122637,4.299770,3.679125
5,16/12/2021 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20,30.75625,3.776868,0.123025,4.301981,0.000000
7,16/12/2021 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20,31.49000,3.866972,0.125960,4.318728,0.000000
8,16/12/2021 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20,0.00000,7.717980,0.251400,5.034488,7.542000
9,16/12/2021 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20,62.97500,7.733330,0.251900,5.037341,0.000000
11,16/12/2021 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20,62.97500,7.733330,0.251900,5.037341,0.000000
12,16/12/2021 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20,0.00000,3.855920,0.125600,4.316674,3.768000
13,16/12/2021 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20,0.00000,3.857455,0.125650,4.316959,3.769500

In [11]:
# Total Charges 
df['Total charges'] = df[['Brokerage','STT/CTT','ETC','SEBI','GST','Stamp charges']].sum(axis=1).round(2)
df

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage,STT/CTT,ETC,SEBI,GST,Stamp charges,Total charges
1,16/12/2021 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20,0.00000,3.858990,0.125700,4.317244,3.771000,32.07
3,16/12/2021 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20,0.00000,3.764971,0.122637,4.299770,3.679125,31.87
5,16/12/2021 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20,30.75625,3.776868,0.123025,4.301981,0.000000,58.96
7,16/12/2021 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20,31.49000,3.866972,0.125960,4.318728,0.000000,59.80
8,16/12/2021 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20,0.00000,7.717980,0.251400,5.034488,7.542000,40.55
9,16/12/2021 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20,62.97500,7.733330,0.251900,5.037341,0.000000,96.00
11,16/12/2021 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20,62.97500,7.733330,0.251900,5.037341,0.000000,96.00
12,16/12/2021 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20,0.00000,3.855920,0.125600,4.316674,3.768000,32.07
13,16/12/2021 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20,0.00000,3.857455,0.125650,4.316959,3.769500,32.07

In [12]:

# we reasign indexing because of 
df = df.reset_index(drop=True)   #  assign back

df.index = range(1, len(df)+1)   # start index from 1

df = df.round(2)

In [13]:
table_1 = df[['Time', 'Type', 'Instrument', 'Product', 'Qty.', 'Avg. price', 'Status', 'Turnover', 
             'Brokerage', 'STT/CTT', 'ETC', 'SEBI', 'GST', 'Stamp charges', 'Total charges']]

table_1

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage,STT/CTT,ETC,SEBI,GST,Stamp charges,Total charges
1,16/12/2021 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20,0.00,3.86,0.13,4.32,3.77,32.07
2,16/12/2021 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20,0.00,3.76,0.12,4.30,3.68,31.87
3,16/12/2021 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20,30.76,3.78,0.12,4.30,0.00,58.96
4,16/12/2021 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20,31.49,3.87,0.13,4.32,0.00,59.80
5,16/12/2021 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20,0.00,7.72,0.25,5.03,7.54,40.55
6,16/12/2021 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20,62.98,7.73,0.25,5.04,0.00,96.00
7,16/12/2021 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20,62.98,7.73,0.25,5.04,0.00,96.00
8,16/12/2021 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20,0.00,3.86,0.13,4.32,3.77,32.07
9,16/12/2021 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20,0.00,3.86,0.13,4.32,3.77,32.07

##Table1

In [14]:

table_1

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage,STT/CTT,ETC,SEBI,GST,Stamp charges,Total charges
1,16/12/2021 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20,0.00,3.86,0.13,4.32,3.77,32.07
2,16/12/2021 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20,0.00,3.76,0.12,4.30,3.68,31.87
3,16/12/2021 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20,30.76,3.78,0.12,4.30,0.00,58.96
4,16/12/2021 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20,31.49,3.87,0.13,4.32,0.00,59.80
5,16/12/2021 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20,0.00,7.72,0.25,5.03,7.54,40.55
6,16/12/2021 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20,62.98,7.73,0.25,5.04,0.00,96.00
7,16/12/2021 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20,62.98,7.73,0.25,5.04,0.00,96.00
8,16/12/2021 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20,0.00,3.86,0.13,4.32,3.77,32.07
9,16/12/2021 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20,0.00,3.86,0.13,4.32,3.77,32.07

In [15]:
# --------------------------------------------------------------------------------------------------------

##Get Data Through Order Table

In [16]:


df_kite = pd.read_excel("kite_PnL_calculated_file.xlsx")

df_kite

,Time,Type,Instrument,Product,Qty.,Avg. price,Status,Turnover,Brokerage,STT/CTT,ETC,SEBI,GST,Stamp charges,Total charges
0,16/12/21 15:08,BUY,ASHOKLEY,MIS,1000,125.70,COMPLETE,125700.0,20,0.00,4.09,0.15,4.36,3.77,32.37
1,16/12/21 14:13,BUY,TATAMOTORS,MIS,250,490.55,COMPLETE,122637.5,20,0.00,3.99,0.14,4.34,3.68,32.15
2,16/12/21 13:54,BUY,ASHOKLEY,MIS,0,127.10,CANCELLED,0.0,0,0.00,0.00,0.00,0.00,0.00,0.00
3,16/12/21 13:21,SELL,TATAMOTORS,MIS,250,492.10,COMPLETE,123025.0,20,30.76,4.00,0.15,4.35,0.00,59.25
4,16/12/21 12:51,BUY,TATAMOTORS,MIS,0,490.80,CANCELLED,0.0,0,0.00,0.00,0.00,0.00,0.00,0.00
5,16/12/21 12:39,SELL,ASHOKLEY,MIS,1000,125.96,COMPLETE,125960.0,20,31.49,4.09,0.15,4.36,0.00,60.10
6,16/12/21 12:29,BUY,ASHOKLEY,MIS,2000,125.70,COMPLETE,251400.0,20,0.00,8.17,0.30,5.12,7.54,41.13
7,16/12/21 11:22,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20,62.98,8.19,0.30,5.13,0.00,96.59
8,16/12/21 10:47,SELL,ASHOKLEY,MIS,0,124.45,CANCELLED,0.0,0,0.00,0.00,0.00,0.00,0.00,0.00
9,16/12/21 10:46,SELL,ASHOKLEY,MIS,2000,125.95,COMPLETE,251900.0,20,62.98,8.19,0.30,5.13,0.00,96.59
10,16/12/21 10:24,BUY,ASHOKLEY,MIS,1000,125.60,COMPLETE,125600.0,20,0.00,4.08,0.15,4.36,3.77,32.36
11,16/12/21 10:23,BUY,ASHOKLEY,MIS,1000,125.65,COMPLETE,125650.0,20,0.00,4.08,0.15,4.36,3.77,32.36

In [17]:
# GRoup by instrument and Type

table_2 = df_kite.groupby(['Instrument', 'Type'], as_index=False).agg({
    'Qty.': 'sum',
    'Turnover': 'sum',
    'Brokerage': 'sum',
    'STT/CTT': 'sum',
    'ETC': 'sum',
    'SEBI': 'sum',
    'GST': 'sum',
    'Stamp charges': 'sum',
    'Total charges': 'sum'
})
table_2

,Instrument,Type,Qty.,Turnover,Brokerage,STT/CTT,ETC,SEBI,GST,Stamp charges,Total charges
0,ASHOKLEY,BUY,5000,628350.0,80,0.00,20.42,0.75,18.20,18.85,138.22
1,ASHOKLEY,SELL,5000,629760.0,60,157.45,20.47,0.75,14.62,0.00,253.28
2,TATAMOTORS,BUY,250,122637.5,20,0.00,3.99,0.14,4.34,3.68,32.15
3,TATAMOTORS,SELL,250,123025.0,20,30.76,4.00,0.15,4.35,0.00,59.25

In [18]:
# Weighted Avg Price = Total Turnover / Total Quantity
table_2['Avg. price'] = (table_2['Turnover'] / table_2['Qty.']).fillna(0)
table_2

,Instrument,Type,Qty.,Turnover,Brokerage,STT/CTT,ETC,SEBI,GST,Stamp charges,Total charges,Avg. price
0,ASHOKLEY,BUY,5000,628350.0,80,0.00,20.42,0.75,18.20,18.85,138.22,125.670
1,ASHOKLEY,SELL,5000,629760.0,60,157.45,20.47,0.75,14.62,0.00,253.28,125.952
2,TATAMOTORS,BUY,250,122637.5,20,0.00,3.99,0.14,4.34,3.68,32.15,490.550
3,TATAMOTORS,SELL,250,123025.0,20,30.76,4.00,0.15,4.35,0.00,59.25,492.100

In [19]:
# reset indexing annd round off
table_2 = table_2.fillna(0)
table_2 = table_2.reset_index(drop=True)
table_2.index = range(1, len(table_2) + 1)
table_2 = table_2.round(2)

In [20]:
# Reorder columns to match requirement
table_2 = table_2[['Instrument', 'Type', 'Qty.', 'Avg. price', 'Turnover',
                   'Brokerage', 'STT/CTT', 'ETC', 'SEBI', 'GST',
                   'Stamp charges', 'Total charges']].round(2)
table_2

,Instrument,Type,Qty.,Avg. price,Turnover,Brokerage,STT/CTT,ETC,SEBI,GST,Stamp charges,Total charges
1,ASHOKLEY,BUY,5000,125.67,628350.0,80,0.00,20.42,0.75,18.20,18.85,138.22
2,ASHOKLEY,SELL,5000,125.95,629760.0,60,157.45,20.47,0.75,14.62,0.00,253.28
3,TATAMOTORS,BUY,250,490.55,122637.5,20,0.00,3.99,0.14,4.34,3.68,32.15
4,TATAMOTORS,SELL,250,492.10,123025.0,20,30.76,4.00,0.15,4.35,0.00,59.25

In [21]:
# --------------------------------------------------------------

In [22]:
# Create separate dataframes for Buy and Sell to calculate PnL

In [23]:

buy = table_2[table_2['Type'] == 'BUY'].groupby('Instrument')['Turnover'].sum()
sell = table_2[table_2['Type'] == 'SELL'].groupby('Instrument')['Turnover'].sum()


# total charges per stock
total_charges = table_2.groupby('Instrument')['Total charges'].sum()


# stock list
stocks = sorted(table_2['Instrument'].unique())


print(buy)
print("-----------------------")
print(sell)
print("-----------------------")
print('-----------------')
print(total_charges)
print('--------------------')
print(stocks)

Instrument
ASHOKLEY      628350.0
TATAMOTORS    122637.5
Name: Turnover, dtype: float64
-----------------------
Instrument
ASHOKLEY      629760.0
TATAMOTORS    123025.0
Name: Turnover, dtype: float64
-----------------------
-----------------
Instrument
ASHOKLEY      391.5
TATAMOTORS     91.4
Name: Total charges, dtype: float64
--------------------
['ASHOKLEY', 'TATAMOTORS']

In [24]:
# ---------------------------------------------------------------

##Crete Table 3

In [26]:
print(stocks)

['ASHOKLEY', 'TATAMOTORS']

In [27]:
table_3= pd.DataFrame(index=stocks)

In [28]:
print(table_3)

Empty DataFrame
Columns: []
Index: [ASHOKLEY, TATAMOTORS]

In [29]:
# calculate Gross Pnl,Total charges adn Net Pnl
table_3['Gross PnL'] = sell.reindex(stocks, fill_value=0) - buy.reindex(stocks, fill_value=0)
table_3['Total charges'] = total_charges.reindex(stocks, fill_value=0)
table_3['Net PnL'] = table_3['Gross PnL'] - table_3['Total charges']

In [30]:
table_3

            Gross PnL  Total charges  Net PnL
ASHOKLEY       1410.0          391.5   1018.5
TATAMOTORS      387.5           91.4    296.1

In [32]:
# Charges %
table_3['% Charges on Gross PnL'] = np.where(
    table_3['Gross PnL'] != 0,
    (table_3['Total charges'] / abs(table_3['Gross PnL'])) * 100,
    0
)
table_3

            Gross PnL  Total charges  Net PnL  % Charges on Gross PnL
ASHOKLEY       1410.0          391.5   1018.5               27.765957
TATAMOTORS      387.5           91.4    296.1               23.587097

In [33]:
# Reindexing  of index column 
table_3 = table_3.reset_index().rename(columns={'index': 'Instrument'})
table_3 = table_3.round(2)

In [34]:
table_3

   Instrument  Gross PnL  Total charges  Net PnL  % Charges on Gross PnL
0    ASHOKLEY     1410.0          391.5   1018.5                   27.77
1  TATAMOTORS      387.5           91.4    296.1                   23.59

In [ ]:
# creating excel file

In [35]:
output_file = "Kite_PnL_Analysis_Report.xlsx"

with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
    table_1.to_excel(writer, sheet_name='Order_Data', index=False)
    table_2.to_excel(writer, sheet_name='Charges_Summary', index=False)
    table_3.to_excel(writer, sheet_name='PnL_Summary', index=False)

In [36]:
from openpyxl import load_workbook
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.utils import get_column_letter

wb = load_workbook(output_file)

for i, sheet in enumerate(wb.sheetnames, start=1):
    ws = wb[sheet]
    
    table_range = f"A1:{get_column_letter(ws.max_column)}{ws.max_row}"
    tab = Table(displayName=f"Table{i}", ref=table_range)
    
    style = TableStyleInfo(
        name="TableStyleMedium9",
        showRowStripes=True,
        showColumnStripes=False
    )
    tab.tableStyleInfo = style
    ws.add_table(tab)

wb.save(output_file)

print("Excel file created successfully")

Excel file created successfully